---
on: push
name: build
permissions: 
  contents: read
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Dockerfilelint
        uses: docker://replicated/dockerfilelint
        with:
          args: Dockerfile

      - name: ShellCheck
        run: shellcheck entrypoint.sh

      - name: Build image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
